branch-protection:
  orgs:
    FitzTheCatalyst:
      repos:
        prowtest:
          protect: true
          branches:
            master:
              protect: true
              required_pull_request_reviews:
                required_approving_review_count: 1